### ISSUE TITLE
Invalid redirect_uri auth error with VS Code Insiders version

### ISSUE THREAD

**Issue by pritamrungta** [linear/linear-vscode-connect-extension#3]
redirect_uri=vscode-insiders://linear.linear-connect/callback

<img width="960" alt="image" src="https://user-images.githubusercontent.com/59230352/216773028-2e038989-5645-472d-ba6b-e904db551b27.png">

Note: This is working perfectly in VS Code Stable version

**Comment by zdaar** [comment]
Also not working in cursor

**Comment by ntindle** [comment]
+1 on the cursor

**Comment by pritamrungta** [comment]
yep, redirect_uri=cursor://linear.linear-connect/callback

@mihar @skbogner

**Comment by skbogner** [comment]
@tarngerine could you take a look? Thanks!

**Comment by tarngerine** [comment]
unfortunately i do not have access to the oauth app to be able to add cursor:// to the redirect_uri. passing to miha who owns it

**Comment by tommoor** [comment]
Should be working now, please confirm

**Comment by pritamrungta** [comment]
confirmed, thanks 👍🏻
